//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvidencijaEksplozivaDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        public int IDOpreme { get; set; }
        public int IDVozila { get; set; }
        public string NazivOpreme { get; set; }
        public System.DateTime DatumKupnje { get; set; }
        public int KolicinaOpreme { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }
    }
}
