//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeResursima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dijelovi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dijelovi()
        {
            this.DijeloviProjektas = new HashSet<DijeloviProjekta>();
        }
    
        public int IDDijela { get; set; }
        public int SerijskiBrojDijelova { get; set; }
        public Nullable<int> KolicinaDijelova { get; set; }
        public bool Ispravnost { get; set; }
    
        public virtual KatalogDijelova KatalogDijelova { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DijeloviProjekta> DijeloviProjektas { get; set; }
    }
}
