//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeResursima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumentacija
    {
        public int IDDOkumentacija { get; set; }
        public string Naziv { get; set; }
        public System.DateTime Rok { get; set; }
        public string Status { get; set; }
        public Nullable<int> IDProjekta { get; set; }
    
        public virtual Projekt Projekt { get; set; }
    }
}
