//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpravljanjeResursima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eksploziv
    {
        public int IDEksploziv { get; set; }
        public string Oznaka { get; set; }
        public string Status { get; set; }
        public string Vrsta { get; set; }
        public decimal Tezina { get; set; }
        public decimal Kolicina { get; set; }
        public Nullable<int> IDProjekta { get; set; }
    
        public virtual Projekt Projekt { get; set; }
    }
}
