login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: ['POST']

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: ['POST', 'GET']

logout:
    path: /api/logout
    controller: App\Controller\AuthController::logout
    methods: ['POST']

get_user:
    path: /api/user
    controller: App\Controller\AuthController::retrieveUser
    methods: ['POST']

user:
    path: /api/user
    controller: App\Controller\UserController
    methods: [GET]
